# Generated by Django 4.2.7 on 2026-04-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnelallocation',
            name='commission_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
