# Generated by Django 4.2.7 on 2026-04-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_personnelallocation_commission_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderextra',
            name='one_time_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
