# Generated by Django 4.2.7 on 2026-04-06 11:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderextra_one_time_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='penalty_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='penalty_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
