# Generated by Django 5.0.6 on 2026-03-18 16:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadingPersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(help_text='Unique employee identification number', max_length=50, unique=True)),
                ('hire_date', models.DateField(auto_now_add=True, help_text='Date when personnel was hired')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this personnel is currently active')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=10.0, help_text='Default commission rate percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('phone_extension', models.CharField(blank=True, default='', help_text='Internal phone extension', max_length=10)),
                ('emergency_contact', models.CharField(blank=True, default='', help_text='Emergency contact name', max_length=100)),
                ('emergency_phone', models.CharField(blank=True, default='', help_text='Emergency contact phone number', max_length=15)),
                ('address', models.TextField(blank=True, default='', help_text='Personnel address')),
                ('notes', models.TextField(blank=True, default='', help_text='Additional notes about personnel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='User account associated with this personnel', on_delete=django.db.models.deletion.CASCADE, related_name='loading_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loading Personnel',
                'verbose_name_plural': 'Loading Personnel',
                'ordering': ['employee_id'],
                'indexes': [models.Index(fields=['employee_id'], name='personnel_l_employe_1538e3_idx'), models.Index(fields=['is_active'], name='personnel_l_is_acti_b4ff33_idx')],
            },
        ),
    ]
