# Generated by Django 4.2.7 on 2026-04-01 19:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='loadingpersonnel',
            name='personnel_l_employe_1538e3_idx',
        ),
        migrations.RemoveIndex(
            model_name='loadingpersonnel',
            name='personnel_l_is_acti_b4ff33_idx',
        ),
        migrations.AlterField(
            model_name='loadingpersonnel',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='loadingpersonnel',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='loadingpersonnel',
            name='emergency_contact',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='loadingpersonnel',
            name='emergency_phone',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='loadingpersonnel',
            name='employee_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='loadingpersonnel',
            name='hire_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='loadingpersonnel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='loadingpersonnel',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='loadingpersonnel',
            name='phone_extension',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='loadingpersonnel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loading_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
