# Generated by Django 4.2.7 on 2026-04-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_remove_loadingpersonnel_personnel_l_employe_1538e3_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadingpersonnel',
            name='employee_id',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
