# Generated by Django 4.2.7 on 2026-04-01 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_alter_loadingpersonnel_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loadingpersonnel',
            name='phone_extension',
        ),
        migrations.AlterField(
            model_name='loadingpersonnel',
            name='emergency_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
