# Generated by Django 4.2.7 on 2026-04-01 22:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0004_remove_loadingpersonnel_phone_extension_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadingpersonnel',
            name='commission_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Deprecated: Use user.commission_rate instead', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
