# Generated by Django 4.2.7 on 2026-04-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='extra',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
