# Generated by Django 4.2.7 on 2026-04-01 22:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Commission rate percentage (0-100). Used for loading personnel.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
